name: second_hand_fashion_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#--------------PACKAGES-----------------#
dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.13
  smooth_page_indicator: ^1.1.0

  #Icon
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #State management
  get: ^4.6.5
  get_storage: ^2.1.1

  #Product specific


#--------------PACKAGES END-----------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  #--------------LOCAL ASSETS-----------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  #--------------LOCAL FONTS-----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
