// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11D12MTx33laVUdof95-sD7-66HKBmMw',
    appId: '1:1088264323064:web:c8c9ef56dbe54838eb600d',
    messagingSenderId: '1088264323064',
    projectId: 'secondhandfashionapp',
    authDomain: 'secondhandfashionapp.firebaseapp.com',
    storageBucket: 'secondhandfashionapp.appspot.com',
    measurementId: 'G-WHVEEW53KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUdkcAoVuY14QgS0Zda76-n402gQjZtBw',
    appId: '1:1088264323064:android:b73f6ac517e37755eb600d',
    messagingSenderId: '1088264323064',
    projectId: 'secondhandfashionapp',
    storageBucket: 'secondhandfashionapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9MDLOmDx-_KJeKYH8QGD3nAC5Jj-AuvE',
    appId: '1:1088264323064:ios:a88079fef3b933bceb600d',
    messagingSenderId: '1088264323064',
    projectId: 'secondhandfashionapp',
    storageBucket: 'secondhandfashionapp.appspot.com',
    androidClientId: '1088264323064-ulnff27hq86vo2ai3nk02sdorhfq9bbl.apps.googleusercontent.com',
    iosClientId: '1088264323064-epq3lnu943bh19k96hntjfesf8qu28af.apps.googleusercontent.com',
    iosBundleId: 'com.hoashopsi.secondHandFashionApp',
  );

}